### ISSUE TITLE
Want to patch/fork First Person mod

### ISSUE THREAD

**Issue by tarnishedmoth** [gjroelofs/valheim-plus-plus-mods#8]
Hey everyone. I am interested in limiting the camera during animation states where you can currently look freely, but your character does not rotate with you, such as Dodge Roll. This is for PvP purposes--the new crossbow weapons can be loaded before a dodge-roll, while rolling you can look directly behind you, and projectiles are always targeted at the crosshair regardless of player facing direction.

Would anyone be willing to patch this in, or allow me to fork the plugin?

**Comment by gjroelofs** [comment]
Feel free to fork it! I'm swamped at the moment so I won't have much time to patch it in myself.

You can open a PR once you have it in if there's a setting to enable/disable it.

**Comment by tarnishedmoth** [comment]
Thanks! I'll start tinkering.

**Comment by tarnishedmoth** [comment]
Could you help me set up the project? The auto/Powershell script is failing me, I manually gathered all the dlls but the project is still breaking from bad references.

**Comment by tarnishedmoth** [comment]
Just realized I can build it in github and just work with the code? What is this sorcery? Very cool.
